version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: pg_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
  app:
    container_name: api
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: 'db'
